from pptx import Presentation
from pptx.util import Inches, Pt


# -----------------------------
# Common Formatting Functions
# -----------------------------

def format_title(shape):
    p = shape.text_frame.paragraphs[0]
    p.font.name = "Calibri"
    p.font.size = Pt(24)
    p.font.bold = True


def format_body(text_frame):
    for paragraph in text_frame.paragraphs:
        paragraph.font.name = "Calibri"
        paragraph.font.size = Pt(14)


# -----------------------------
# PPT Generator
# -----------------------------

def create_ppt(
    company_name,
    report_date,
    total_budget,
    total_actual,
    total_variance,
    ebitda,
    commentary
):

    prs = Presentation()

    # ===================================
    # Slide 1 - Cover Page
    # ===================================

    slide = prs.slides.add_slide(
        prs.slide_layouts[0]
    )

    slide.shapes.title.text = company_name
    format_title(slide.shapes.title)

    slide.placeholders[1].text = (
        f"Board Performance Report\n\n"
        f"Reporting Date: {report_date}\n\n"
        f"Generated by BoardPackAI"
    )

    format_body(
        slide.placeholders[1].text_frame
    )

    # ===================================
    # Slide 2 - Executive Summary
    # ===================================

    slide = prs.slides.add_slide(
        prs.slide_layouts[1]
    )

    slide.shapes.title.text = "Executive Summary"
    format_title(slide.shapes.title)

    slide.placeholders[1].text = f"""
Financial performance for {company_name}
was reviewed against budget.

KEY HIGHLIGHTS

• Total Budget: {total_budget:,.0f}

• Total Actual: {total_actual:,.0f}

• EBITDA: {ebitda:,.0f}

• Total Variance: {total_variance:,.0f}

Overall performance remains within
management expectations.
"""

    format_body(
        slide.placeholders[1].text_frame
    )

    # ===================================
    # Slide 3 - KPI Dashboard
    # ===================================

    slide = prs.slides.add_slide(
        prs.slide_layouts[5]
    )

    slide.shapes.title.text = "KPI Dashboard"
    format_title(slide.shapes.title)

    textbox = slide.shapes.add_textbox(
        Inches(1),
        Inches(1.2),
        Inches(6),
        Inches(3)
    )

    textbox.text_frame.text = f"""
BUDGET
{total_budget:,.0f}

ACTUAL
{total_actual:,.0f}

VARIANCE
{total_variance:,.0f}

EBITDA
{ebitda:,.0f}
"""

    format_body(
        textbox.text_frame
    )

    # ===================================
    # Slide 4 - Financial Performance
    # ===================================

    slide = prs.slides.add_slide(
        prs.slide_layouts[5]
    )

    slide.shapes.title.text = (
        "Financial Performance"
    )

    format_title(
        slide.shapes.title
    )

    slide.shapes.add_picture(
        "budget_vs_actual.png",
        Inches(0.5),
        Inches(1.2),
        width=Inches(8.5)
    )

    # ===================================
    # Slide 5 - Key Insights
    # ===================================

    slide = prs.slides.add_slide(
        prs.slide_layouts[1]
    )

    slide.shapes.title.text = "Key Insights"
    format_title(slide.shapes.title)

    slide.placeholders[1].text = """
• Revenue exceeded budget expectations.

• Key variances identified automatically.

• Financial performance remains positive.

• EBITDA performance supports growth strategy.
"""

    format_body(
        slide.placeholders[1].text_frame
    )

    # ===================================
    # Slide 6 - Risks & Opportunities
    # ===================================

    slide = prs.slides.add_slide(
        prs.slide_layouts[1]
    )

    slide.shapes.title.text = (
        "Risks & Opportunities"
    )

    format_title(
        slide.shapes.title
    )

    slide.placeholders[1].text = """
RISKS

• Expense growth above budget

• Cost overruns in selected accounts

• Margin pressure


OPPORTUNITIES

• Revenue expansion

• Cost optimization

• Productivity improvements
"""

    format_body(
        slide.placeholders[1].text_frame
    )

    # ===================================
    # Slide 7 - AI Commentary
    # ===================================

    slide = prs.slides.add_slide(
        prs.slide_layouts[5]
    )

    slide.shapes.title.text = (
        "AI Executive Commentary"
    )

    format_title(
        slide.shapes.title
    )

    textbox = slide.shapes.add_textbox(
        Inches(0.5),
        Inches(1.0),
        Inches(8.5),
        Inches(4.5)
    )

    text_frame = textbox.text_frame
    text_frame.word_wrap = True

    p = text_frame.paragraphs[0]
    p.text = commentary
    p.font.name = "Calibri"
    p.font.size = Pt(14)

    # ===================================
    # Slide 8 - Recommendations
    # ===================================

    slide = prs.slides.add_slide(
        prs.slide_layouts[1]
    )

    slide.shapes.title.text = (
        "Management Recommendations"
    )

    format_title(
        slide.shapes.title
    )

    slide.placeholders[1].text = """
1. Review high-variance accounts.

2. Strengthen cost control initiatives.

3. Continue investment in growth areas.

4. Monitor EBITDA performance monthly.

5. Track KPIs against budget.
"""

    format_body(
        slide.placeholders[1].text_frame
    )

    filename = "board_pack.pptx"

    prs.save(filename)

    return filename